# Generated by Django 5.2.9 on 2025-12-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GazeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_signature', models.TextField(blank=True, null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrollment_samples', models.IntegerField(default=0)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('auth_threshold', models.FloatField(default=0.7)),
                ('use_gaze_auth', models.BooleanField(default=False)),
                ('successful_auths', models.IntegerField(default=0)),
                ('failed_auths', models.IntegerField(default=0)),
                ('last_auth_date', models.DateTimeField(blank=True, null=True)),
                ('svm_model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cnn_model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gaze_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gaze Profile',
                'verbose_name_plural': 'Gaze Profiles',
            },
        ),
        migrations.CreateModel(
            name='GazeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('authentication', 'Authentication'), ('calibration', 'Calibration')], max_length=20)),
                ('features_data', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaze_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gaze Session',
                'verbose_name_plural': 'Gaze Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
